// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package abe

// Injectors from wire.go:

// InitializeEngine 初始化并返回 abe 框架的应用引擎实例
//
// 此函数是 abe 框架的入口函数，负责创建和组装所有核心组件，包括：
//   - 配置系统（支持命令行参数、环境变量、配置文件）
//   - 日志系统（结构化日志，支持控制台和文件输出）
//   - HTTP 路由（基于 Gin 框架）
//   - 数据库连接（基于 GORM）
//   - 定时任务调度器（基于 Cron）
//
// 重要提示：
//   - 此函数应该在应用启动时仅调用一次（通常在 main 函数中）
//   - 返回的 Engine 实例包含所有共享服务，应在整个应用中复用
//   - 多次调用会创建多个独立的引擎实例，可能导致资源浪费和行为不一致
//
// 使用示例：
//
//	func main() {
//	    engine := abe.InitializeEngine()
//	    // 配置路由、定时任务等
//	    engine.Run()  // 启动 HTTP 服务器和定时任务调度器
//	}
func InitializeEngine() *Engine {
	viper := newConfig()
	logger := newLogger(viper)
	engine := newRouter(viper, logger)
	db := newDB(viper)
	cron := newCron(logger)
	config := newGoChannelConfig(viper)
	loggerAdapter := newGoChannelLogger(logger)
	abeGoChannelBus := newGoChannelBus(config, loggerAdapter)
	pool := newPool(viper, logger)
	enforcer := newEnforcer(db, logger, viper)
	validator := newValidator(viper)
	middlewareManager := newMiddlewareManager()
	bundle := newI18nBundle(viper, logger)
	authManager := newAuthManager(viper, enforcer, db)
	dynamicConfigManager := newDynamicConfigManager(db, viper, logger)
	rootScope := newRootScope(viper, db, abeGoChannelBus, pool, logger, enforcer)
	abeEngine := &Engine{
		config:            viper,
		router:            engine,
		db:                db,
		cron:              cron,
		events:            abeGoChannelBus,
		pool:              pool,
		logger:            logger,
		enforcer:          enforcer,
		validator:         validator,
		middlewareManager: middlewareManager,
		i18nBundle:        bundle,
		authManager:       authManager,
		dynamicConfig:     dynamicConfigManager,
		rootScope:         rootScope,
	}
	return abeEngine
}
